# Document配置信息
swagger:
  # 文档标题
  title: Aurora
  # 组织信息
  group-name: Aurora-Swagger
  # 是否开启
  enable: true
  # 描述信息
  describe: Aurora测试API接口平台
  # 版本信息
  version: Release 1.0.0
  # 扫包路径
  scan-package: com.aurora.controller
  # 组织信息
  terms-of-service-url: https://www.xiaogong.xyz
  # 联系人作者
  contact-name: 城北花开
  # 链接
  contact-url: https://github.com/xx123-haha/blog
  # 邮箱
  contact-email: 18230615417@163.com

# knife4j配置
knife4j:
  # 开启增强配置
  enable: true

